# Project basic info
sonar.projectKey=Abhi17np_pms_project1
sonar.organization=abhi17np

# Only scan source folder (important)
sonar.sources=pms_project


# Exclude heavy/unnecessary folders
sonar.exclusions=**/node_modules/**,**/venv/**,**/env/**,**/__pycache__/**,**/build/**,**/dist/**,**/*.pt,**/*.h5,**/datasets/**,**/models/**,**/*.log

